version: '3'

services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5890:5890"
    depends_on:
      - redis
    volumes:
      - ${PWD}/me.json:/app/me.json

  redis:
    container_name: redis
    image: redis
    volumes:
      - redis_data:/data

volumes:
  redis_data: